version: '3.8'

services:
  web:
    build: ./backend
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./deploy/django:/home/app/database # to persist sqlite database
      - ./deploy/django/staticfiles:/home/app/staticfiles # to persist static files
      - ./deploy/django/mediafiles:/home/app/mediafiles # to persist media files
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - ./deploy/postgres_db/:/var/lib/postgresql/data
      - ./deploy/postgres_db_dump/:/var/lib/postgresql/dump/
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PORT: ${DATABASE_PORT}

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
