version: '3.8'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./deploy/django:/code/database # to persist sqlite database
      - ./deploy/django/staticfiles:/code/staticfiles # to persist static files
      - ./deploy/django/mediafiles:/code/mediafiles # to persist media files
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    build: ./database
    restart: always
    container_name: postgres
    volumes:
      - ./deploy/postgres_db/:/var/lib/postgresql/data
      - ./deploy/postgres_db_dump/:/var/lib/postgresql/dump/
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PORT: ${DATABASE_PORT}

volumes:
  postgres_data:
