version: '3.8'

services:
  django:
    build: ./backend
    container_name: django
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./deploy/django/staticfiles:/home/app/staticfiles # to persist static files
      - ./deploy/django/mediafiles:/home/app/mediafiles # to persist media files
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - postgres

  postgres:
    image: postgres:13.0-alpine
    container_name: postgres_db
    volumes:
      - ./deploy/postgres_db/:/var/lib/postgresql/data
      - ./deploy/postgres_db_dump/:/var/lib/postgresql/dump/
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PORT: ${DATABASE_PORT}

  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - ./deploy/django/staticfiles:/staticfiles:ro # to serve django static content
      - ./deploy/django/mediafiles:/mediafiles:ro # to serve django users media
    ports:
      - 1337:80
    depends_on:
      - django

volumes:
  postgres_data:
  static_volume:
  media_volume:
