# Generated by Django 4.1.2 on 2022-10-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressbr',
            options={'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.AlterModelOptions(
            name='historic',
            options={'verbose_name': 'Histórico', 'verbose_name_plural': 'Históricos'},
        ),
        migrations.AlterField(
            model_name='historic',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
    ]
