# Generated by Django 4.1.2 on 2022-10-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_addressbr_options_alter_historic_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakemodeltest',
            name='test',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
