# Generated by Django 4.1.2 on 2022-10-12 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_fakemodeltest_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakemodeltest',
            name='test_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.fakemodeltest'),
        ),
    ]
