# Generated by Django 4.1.2 on 2022-10-15 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_fakemodeltest_test_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbr',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='addressbr',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deletado em'),
        ),
        migrations.AlterField(
            model_name='addressbr',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado'),
        ),
        migrations.AlterField(
            model_name='addressbr',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='fakemodeltest',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='fakemodeltest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deletado em'),
        ),
        migrations.AlterField(
            model_name='fakemodeltest',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado'),
        ),
        migrations.AlterField(
            model_name='fakemodeltest',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='historic',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='historic',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deletado em'),
        ),
        migrations.AlterField(
            model_name='historic',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado'),
        ),
        migrations.AlterField(
            model_name='historic',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Atualizado em'),
        ),
    ]
